### ISSUE TITLE
Feature Request: Opt-out/remove throwing of runtime errors

### ISSUE THREAD

**Issue by magicgrl111** [segmentio/typewriter#54]
Our application is written in TypeScript and since we use the typewriter-generated type definitions during development and transpilation, throwing runtime errors is unnecessary and introduces instability into the execution of our application.  If an analytics event is mis-typed at runtime, I would prefer it not block execution of other application code.  Currently, the only way to safeguard these calls would be to wrap each function call in a try/catch and that feels like a lot of unnecessary code that would be better to build into the library itself. It would be very beneficial to have the throwing of runtime errors be configurable or removed entirely.

Happy to provide more information if needed and thanks for the hard work!

**Comment by colinking** [comment]
Glad to hear you're experimenting with Typewriter, @magicgrl111! You bring up a bunch of great points:

### Runtime validation in a strongly-typed language

Depending on your use of JSON Schema, there are a number of types of analytics validation that can only happen at runtime -- for example, regex validation of string values. So there is some value to be had in runtime validation, even with languages like TypeScript.

### Disabling runtime validation in production

We 100% agree this is something that you may not want to run during production, and for that there's the `--runtimeValidation` flag that takes a boolean:

```
typewriter gen-js \
  --inputPath ./schema.json \
  --outputPath ./generated \
  --declarations ts \
  --runtimeValidation false
```

For example, this is how we configure `--runtimeValidation` in one of our Makefiles at Segment:

```
$(BIN)/typewriter gen-js \
	--inputPath ./client/analytics/typewriter/generated/app.json \
	--outputPath ./client/analytics/typewriter/generated \
	--declarations ts \
	--runtimeValidation $(shell if [ "$(NODE_ENV)" = "production" ]; then echo "false"; else echo "true"; fi)
```

### Error Behavior

With runtime validation, the default behavior in the JS clients is to throw errors, however we just recently made that customizable with an `onError` option that allows you to do things, like logging your errors instead of throwing: https://github.com/segmentio/typewriter/pull/52

For example, you can configure this hook to `console.error` during development and throw errors during testing, based on the value of `NODE_ENV`.

Just keep in mind that this handler won't fire if `--runtimeValidation` is disabled.

### Documentation

I know neither method is well documented, so I'll look into updating our README to include information about both options.

Let me know if this works for you and your team!

**Comment by magicgrl111** [comment]
@colinking Thanks for the quick response, this is exactly what we need! So glad to hear this is a case you've already considered.  The runtimeValidation and onError options are both going to be very useful to us. Definitely would +1 adding documentation around those to the Readme so others can more easily find those features.  Thanks again!
