### ISSUE TITLE
is it possible to use Typewriter outside of segment?

### ISSUE THREAD

**Issue by drkhannah** [segmentio/typewriter#84]
is it possible to use Typewriter outside of segment?

not having to use a segment token?

possibly building types for a for a analytics library that is similar to Segment, but custom.

something like, MyCustomAnalyticsLib.orderCompleted()

**Comment by colinking** [comment]
Hey @drkhannah! You could probably hack around it a bit, but at least for now, we're focusing on making the experience as smooth as possible for Segment Tracking Plan users :)

Haven't tried any of this, but you might be able to:
- Add a `typewriter.yml` with your client config. IIRC there's validation requiring at least one Tracking Plan, so add one with any id/workspace_slug (doesn't matter what you use) and set the path to wherever you want your client.
- Manually add JSON Schema for your events to a `plan.json` in that directory
- Then you can use `typewriter build` and `typewriter prod` (these will use your `plan.json` instead of querying the API, as long as one exists locally)

**Comment by securingsincity** [comment]
I haven't tried with version 7 but with version 6 you could create a schema.json file based on your events and then run `typewriter gen-js  --inputPath ./schema.json --outputPath ./generated  --declarations ts --module CommonJS`. I'll try migrating a project to version 7 and see if @colinking 's comment works

**Comment by securingsincity** [comment]
Can confirm if all you want to do is take a plan you wrote yourself as `plan.json` you can do that following @colinking 's steps
